const {test}=require('node:test');const a=require('node:assert/strict');const d=require('../src/domain.cjs');
const accounts=[{id:'cash',name:'Cash',opening:10000,archived:false},{id:'bank',name:'Bank',opening:0,archived:false}];
function tx(type,amount,extra={}){return {id:Math.random().toString(),type,amount,date:'2026-10-07',accountId:'cash',destinationId:'',categoryId:type==='income'?'salary':'food',note:'',tags:'',createdAt:'2026-10-07T12:00:00Z',updatedAt:'2026-10-07T12:00:00Z',deletedAt:null,...extra};}
test('decimal parsing stays exact and rejects ambiguous or unsafe input',()=>{a.equal(d.moneyToMinor('0.29'),29);a.equal(d.moneyToMinor('48.50'),4850);a.equal(d.moneyToMinor('12.3'),1230);for(const s of ['0','-1','1.001','1e4','NaN','1,234','99999999999999'])a.throws(()=>d.moneyToMinor(s));a.equal(d.signedMoneyToMinor('-10.25'),-1025);});
test('refunds reduce spending; transfers never inflate income or expenses',()=>{const list=[tx('expense',4850),tx('income',100000),tx('refund',850),tx('transfer',2000,{destinationId:'bank'})];a.deepEqual(d.summary(list),{expenses:4850,refunds:850,spending:4000,income:100000,net:96000});a.equal(d.accountBalance(accounts[0],list),104000);a.equal(d.accountBalance(accounts[1],list),2000);});
test('calendar dates and leap years are validated',()=>{a.equal(d.validDate('2024-02-29'),true);a.equal(d.validDate('2026-02-29'),false);a.equal(d.validDate('2026-13-01'),false);a.equal(d.validDate('2026-10-7'),false);a.equal(d.dayCount('2026-10-01','2026-10-07'),7);a.deepEqual(d.monthBounds('2024-02-02'),{from:'2024-02-01',to:'2024-02-29'});});
test('filters match date, account including transfer destination, and notes',()=>{const list=[tx('expense',100,{note:'Weekly groceries'}),tx('expense',200,{date:'2026-09-01'}),tx('transfer',300,{destinationId:'bank'}),tx('expense',400,{deletedAt:'now'})];a.equal(d.filterTransactions(list,{from:'2026-10-01',to:'2026-10-31',search:'groceries'}).length,1);a.equal(d.filterTransactions(list,{accountId:'bank'}).length,1);a.equal(d.filterTransactions(list,{}).length,3);});
test('same-account transfers and wrong category types are rejected',()=>{a.throws(()=>d.validateTransaction(tx('transfer',100,{destinationId:'cash'}),accounts,d.CATEGORY_SEEDS));a.throws(()=>d.validateTransaction(tx('expense',100,{categoryId:'salary'}),accounts,d.CATEGORY_SEEDS));d.validateTransaction(tx('transfer',100,{destinationId:'bank'}),accounts,d.CATEGORY_SEEDS);});
test('deleted transactions are absent from balances and category totals',()=>{const list=[tx('expense',100),tx('refund',200),tx('income',900),tx('expense',9999,{deletedAt:'now'})];a.equal(d.categoryTotals(list)[0].amount,-100);a.equal(d.accountBalance(accounts[0],list),11000);});
function snap(){return {format:'moneywise-backup',version:1,data:{accounts,categories:d.CATEGORY_SEEDS,transactions:[tx('expense',100)],budgets:[],notes:[],goals:[],settings:{currency:'USD',name:'Friend'}}};}
test('restore validation rejects duplicate IDs, invalid references and newer formats',()=>{a.ok(d.validateSnapshot(snap()));const s=snap();s.data.transactions.push({...s.data.transactions[0]});a.throws(()=>d.validateSnapshot(s));const b=snap();b.data.transactions[0].accountId='missing';a.throws(()=>d.validateSnapshot(b));const c=snap();c.version=99;a.throws(()=>d.validateSnapshot(c));});

test('custom categories and appearance survive backup validation',()=>{
 const s=snap();s.data.categories.push({id:'pets',name:'Pets',type:'expense',icon:'heart',color:'#7543BA'});
 s.data.transactions[0].categoryId='pets';s.data.settings.theme='dark';s.data.settings.primaryColor='#7543BA';
 a.equal(d.validateSnapshot(s),s);a.equal(s.data.transactions[0].categoryId,'pets');
 s.data.settings.theme='unknown';a.throws(()=>d.validateSnapshot(s));s.data.settings.theme='light';
 s.data.settings.primaryColor='invalid';a.throws(()=>d.validateSnapshot(s));
});
