import React,{useState} from 'react';
import {View,Text,Pressable} from 'react-native';
import {Field,Btn,Chip,Icon,C,s,PRIMARY_COLORS,Sheet,EXTRA_ICONS} from './ui';
import {useApp} from './context';
import * as Store from './store';
import type {Category} from './models';
export function CategoryForm({existing,type='expense',fixedType=false,onClose}:{existing?:Category;type?:'expense'|'income';fixedType?:boolean;onClose:(id?:string)=>void}){
 const [iconsOpen,setIconsOpen]=useState(false);
 const {ledger,act,busy}=useApp();const [name,setName]=useState(existing?.name||'');const [kind,setKind]=useState(existing?.type||type);const [icon,setIcon]=useState(existing?.icon||'basket');const [color,setColor]=useState(existing?.color||C.teal);
 return <><Field label="Category name" value={name} onChangeText={setName} maxLength={40} placeholder="e.g. Pets or subscriptions"/><Text style={s.label}>Category type</Text><View style={{flexDirection:'row'}}>{(['expense','income'] as const).map(t=><Chip key={t} title={t==='expense'?'Expense':'Income'} selected={kind===t} onPress={()=>{if(!existing&&!fixedType)setKind(t);}}/>)}</View>{existing&&<Text style={[s.muted,{marginBottom:16}]}>The type stays the same to preserve existing transactions.</Text>}<Text style={s.label}>Icon</Text><View style={[s.row,{justifyContent:'flex-start',marginBottom:12}]}><Icon name={icon} color={color}/><Text style={s.muted}>Selected: {icon}</Text></View><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:16}}>{['basket','cup','car','bag','heart','star','work','gift','wallet','home','target','dots'].map(i=><Pressable key={i} accessibilityRole="button" accessibilityLabel={i} accessibilityState={{selected:icon===i}} onPress={()=>i==='dots'?setIconsOpen(true):setIcon(i)} style={[s.input,{borderColor:icon===i?C.teal:C.line}]}><Icon name={i} color={color}/></Pressable>)}</View><Text style={s.label}>Color</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:20}}>{Array.from(new Set([...PRIMARY_COLORS,color])).map(c=><Pressable key={c} accessibilityRole="button" accessibilityLabel={`Color ${c}`} accessibilityState={{selected:color===c}} onPress={()=>setColor(c)} style={{width:48,height:48,borderRadius:24,backgroundColor:c,alignItems:'center',justifyContent:'center'}}>{color===c&&<Icon name="check" color="white"/>}</Pressable>)}</View><Btn title={existing?'Save category':'Add category'} disabled={busy} onPress={async()=>{const id=existing?.id||Store.id();if(await act(()=>Store.saveCategory({id,name,icon,color,type:kind},ledger)))onClose(id);}}/><Sheet visible={iconsOpen} title="More category icons" onClose={()=>setIconsOpen(false)}><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{EXTRA_ICONS.map(i=><Pressable key={i} accessibilityRole="button" accessibilityLabel={i} onPress={()=>{setIcon(i);setIconsOpen(false);}} style={[s.input,{width:'30%',alignItems:'center',borderColor:icon===i?C.teal:C.line}]}><Icon name={i} color={color}/><Text style={[s.muted,{fontSize:11,marginTop:6}]}>{i}</Text></Pressable>)}</View></Sheet></>;
}
