import * as Local from './local';
import {currentTime} from './TimeField';
import {CategoryGrid} from './CategoryGrid';
import {DateField} from './DateField';
import {CategoryForm} from './CategoryForm';
import React,{useState} from 'react';
import {Text,View,Pressable,Alert,ScrollView,Image,Switch} from 'react-native';
import {useApp} from './context';
import {Card,Chip,Field,Btn,Icon,C,s,Section,Sheet} from './ui';
import * as Store from './store';
import {moneyToMinor,signedMoneyToMinor,minorToInput,today,formatMoney,validDate} from './domain.cjs';
import type {Transaction,TxType,Account,Budget,Goal,EntryTemplate} from './models';
export function TransactionForm({existing,initialTemplate,onClose,onDrag}:{existing?:Transaction;initialTemplate?:EntryTemplate;onClose:()=>void;onDrag:(active:boolean)=>void}){
 const {ledger,act,busy,undo}=useApp();
 const [type,setType]=useState<TxType>(existing?.type||initialTemplate?.type||'expense');const [amount,setAmount]=useState(existing?minorToInput(existing.amount):initialTemplate?minorToInput(initialTemplate.amount):'');
 const [category,setCategory]=useState(existing?.categoryId||initialTemplate?.categoryId||'food');const [account,setAccount]=useState(existing?.accountId||initialTemplate?.accountId||ledger.settings.lastAccountId||ledger.accounts.find(a=>!a.archived)?.id||'cash');
 const [destination,setDestination]=useState(existing?.destinationId||initialTemplate?.destinationId||ledger.accounts.find(a=>!a.archived&&a.id!==account)?.id||'');
 const [categoryEditor,setCategoryEditor]=useState<'new'|'edit'|null>(null);
 const [time,setTime]=useState(existing?.time||(existing?'':currentTime()));
 const [date,setDate]=useState(existing?.date||today());const [note,setNote]=useState(existing?.note||initialTemplate?.note||'');const [tags,setTags]=useState(existing?.tags||initialTemplate?.tags||'');
 const [receipt,setReceipt]=useState(existing?.receipt);const [refundOf,setRefundOf]=useState(existing?.refundOfId||'');const [optional,setOptional]=useState(!!existing);const [templateName,setTemplateName]=useState('');const [templateOpen,setTemplateOpen]=useState(false);
 function applyTemplate(t:EntryTemplate){setType(t.type);setAmount(minorToInput(t.amount));setCategory(t.categoryId);setAccount(t.accountId);setDestination(t.destinationId);setNote(t.note);setTags(t.tags);}
 function changeType(t:TxType){setType(t);setCategory(t==='income'?'salary':'food');}
 async function save(duplicate=false){if(await act(async()=>{if(!validDate(date))throw new Error('Choose a valid date.');const now=new Date().toISOString();const t:Transaction={id:duplicate||!existing?Store.id():existing.id,type,amount:moneyToMinor(amount),date,...(time?{time}:{}),categoryId:type==='transfer'?'':category,accountId:account,destinationId:type==='transfer'?destination:'',note:note.trim(),tags:tags.trim(),receipt,...(type==='refund'&&refundOf?{refundOfId:refundOf}:{}),occurredAt:time?new Date(date+'T'+time+':00').toISOString():undefined,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,createdAt:duplicate||!existing?now:existing.createdAt,updatedAt:now,deletedAt:null};if(t.refundOfId&&!ledger.transactions.some(x=>x.id===t.refundOfId&&x.type==='expense'&&!x.deletedAt))throw new Error('Choose an existing expense for the refund.');await Store.saveTransaction(t,ledger);await Store.saveSettings({...ledger.settings,lastAccountId:account});}))onClose();}
 function remove(){if(existing)Alert.alert('Delete transaction?','You can undo this deletion immediately.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{if(await act(()=>Store.deleteTransaction(existing))){undo(existing);onClose();}}}]);}
 return <>{!existing&&<><ScrollView horizontal showsHorizontalScrollIndicator={false}>{(ledger.settings.templates||[]).map(t=><Chip key={t.id} title={t.name} selected={false} onPress={()=>applyTemplate(t)}/>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false}>{Array.from(new Set(ledger.transactions.filter(t=>!t.deletedAt&&t.type===type).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(t=>t.categoryId))).slice(0,5).map(id=>{const c=ledger.categories.find(c=>c.id===id);return c?<Chip key={id} title={'Recent: '+c.name} selected={category===id} onPress={()=>setCategory(id)}/>:null;})}</ScrollView></>}<View style={{flexDirection:'row',flexWrap:'wrap'}}>{(['expense','income','transfer','refund'] as TxType[]).map(t=><Chip key={t} title={t[0].toUpperCase()+t.slice(1)} selected={type===t} onPress={()=>changeType(t)}/>)}</View>
 <Card style={{marginTop:8}}><Text style={s.label}>Amount ({ledger.settings.currency})</Text><Field label="" value={amount} onChangeText={setAmount} placeholder="0.00" keyboardType="decimal-pad" maxLength={15}/><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{['1','2','3','4','5','6','7','8','9','.','0','⌫'].map(key=><Pressable key={key} accessibilityLabel={key==='⌫'?'Backspace':key} onPress={()=>{if(key==='⌫')setAmount(v=>v.slice(0,-1));else if(key!=='.'||!amount.includes('.'))setAmount(v=>(v+key).slice(0,15));}} style={{width:'31%',flexGrow:1,backgroundColor:C.bg,borderRadius:10,padding:13,alignItems:'center'}}><Text style={[s.text,{fontWeight:'700',fontSize:19}]}>{key}</Text></Pressable>)}</View></Card>
 {type!=='transfer'&&<><Section title="Category"/><Text style={[s.muted,{marginBottom:8}]}>Hold and drag to arrange your categories.</Text><CategoryGrid categories={ledger.categories.filter(c=>c.type===(type==='income'?'income':'expense')).sort((a,b)=>(a.order??ledger.categories.indexOf(a))-(b.order??ledger.categories.indexOf(b)))} selected={category} onSelect={setCategory} onAdd={()=>setCategoryEditor('new')} onReorder={ids=>act(()=>Store.saveCategoryOrder(ids,ledger))} onDrag={onDrag}/></>}
 <Section title={type==='transfer'?'From payment type':'Payment type'}/><View style={{flexDirection:'row',flexWrap:'wrap'}}>{ledger.accounts.filter(a=>!a.archived||a.id===account).map(a=><Chip key={a.id} title={a.type==='Bank'&&a.name==='Account'?'Account':a.name} selected={a.id===account} onPress={()=>setAccount(a.id)}/>)}</View>
 {type==='transfer'&&<><Section title="To account"/><View style={{flexDirection:'row',flexWrap:'wrap'}}>{ledger.accounts.filter(a=>!a.archived&&a.id!==account).map(a=><Chip key={a.id} title={a.name} selected={a.id===destination} onPress={()=>setDestination(a.id)}/>)}</View>{ledger.accounts.filter(a=>!a.archived).length<2&&<Text style={[s.muted,{marginBottom:12}]}>Add another account in More → Accounts to make a transfer.</Text>}</>}
 <View style={{marginTop:18}}><DateField label="Date & time" value={date} onChangeText={setDate} time={time} onTimeChange={setTime}/><Btn title={optional?'Hide optional details':'Notes, tags and receipt'} secondary onPress={()=>setOptional(!optional)}/>{optional&&<><Field label="Note (optional)" value={note} onChangeText={setNote} multiline placeholder="What was this for?"/><Field label="Tags (optional, comma separated)" value={tags} onChangeText={setTags} placeholder="work, family, trip" maxLength={300}/><Btn secondary title={receipt?"Replace receipt":"Attach receipt image"} onPress={()=>act(async()=>{const path=await Local.pickReceipt();if(path)setReceipt(path);})}/>{receipt&&<><Image source={{uri:"file://"+receipt}} resizeMode="contain" style={{height:180,width:"100%",marginBottom:12}}/><Btn secondary title="Remove receipt" onPress={()=>setReceipt(undefined)}/></>}</>}</View>
 {type==='refund'&&<><Text style={s.label}>Original expense (optional)</Text><ScrollView horizontal><Chip title="Unlinked refund" selected={!refundOf} onPress={()=>setRefundOf('')}/>{ledger.transactions.filter(t=>t.type==='expense'&&!t.deletedAt).slice(0,30).map(t=><Chip key={t.id} title={t.date+' · '+formatMoney(t.amount,ledger.settings.currency)} selected={refundOf===t.id} onPress={()=>{setRefundOf(t.id);setCategory(t.categoryId);setAccount(t.accountId);}}/>)}</ScrollView><Text style={[s.muted,{marginBottom:16}]}>A refund reduces spending in the selected category and increases the account balance.</Text></>}
 <Btn title={busy?'Saving…':existing?'Save changes':`Save ${type}`} disabled={busy} onPress={()=>save()}/>{existing&&<><Btn title="Save as a new transaction" secondary disabled={busy} onPress={()=>save(true)}/><Btn title="Delete transaction" danger disabled={busy} onPress={remove}/></>}
 <Btn secondary title="Save as reusable template" disabled={busy} onPress={()=>setTemplateOpen(true)}/><Sheet visible={templateOpen} title="Save template" onClose={()=>setTemplateOpen(false)}><Field label="Template name" value={templateName} onChangeText={setTemplateName} maxLength={80}/><Btn title="Save template" disabled={busy} onPress={()=>act(async()=>{await Store.saveTemplate({id:Store.id(),name:templateName.trim(),type,amount:moneyToMinor(amount),accountId:account,destinationId:destination,categoryId:type==='transfer'?'':category,note:note.trim(),tags:tags.trim()},ledger);setTemplateOpen(false);setTemplateName('');})}/></Sheet>
 <Sheet visible={!!categoryEditor} title={categoryEditor==='edit'?'Edit category':'Add category'} onClose={()=>setCategoryEditor(null)}><CategoryForm fixedType key={`${categoryEditor}-${category}`} existing={categoryEditor==='edit'?ledger.categories.find(c=>c.id===category):undefined} type={type==='income'?'income':'expense'} onClose={id=>{if(id)setCategory(id);setCategoryEditor(null);}}/></Sheet>
 </>;
}
export function AccountForm({existing,onClose}:{existing?:Account;onClose:()=>void}){
 const {act,busy}=useApp();const [name,setName]=useState(existing?.name||'');const [type,setType]=useState(existing?.type||'Cash');const [opening,setOpening]=useState(existing?minorToInput(existing.opening):'0');
 async function save(archived=existing?.archived||false){if(await act(()=>Store.saveAccount({id:existing?.id||Store.id(),name:name.trim(),type,opening:signedMoneyToMinor(opening),archived})))onClose();}
 return <><Field label="Account name" value={name} onChangeText={setName} placeholder="Cash, bank, credit card…" maxLength={80}/><Text style={s.label}>Account type</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['Cash','Bank','Card','Wallet'].map(t=><Chip key={t} title={t} selected={type===t} onPress={()=>setType(t)}/>)}</View><View style={{marginTop:14}}><Field label="Opening balance" value={opening} onChangeText={setOpening} placeholder="0.00" keyboardType="numbers-and-punctuation"/></View><Text style={[s.muted,{marginBottom:20}]}>Use a negative opening balance for money owed on a card. Card repayments are transfers, not expenses.</Text><Btn title="Save account" disabled={busy} onPress={()=>save()}/>{existing&&<Btn title={existing.archived?'Unarchive account':'Archive account'} secondary disabled={busy} onPress={()=>{Alert.alert(existing.archived?'Unarchive account?':'Archive account?','Existing transactions and balances are preserved.',[{text:'Cancel',style:'cancel'},{text:'Continue',onPress:()=>save(!existing.archived)}]);}}/>}</>;
}
export function BudgetForm({existing,onClose}:{existing?:Budget;onClose:()=>void}){
 const {ledger,act,busy}=useApp();const [name,setName]=useState(existing?.name||'Monthly budget');const [amount,setAmount]=useState(existing?minorToInput(existing.amount):'');const [category,setCategory]=useState(existing?.categoryId||'');
 const [period,setPeriod]=useState<NonNullable<Budget['period']>>(existing?.period||'monthly');const [start,setStart]=useState(existing?.startDate||today());const [end,setEnd]=useState(existing?.endDate||today());const [rollover,setRollover]=useState(existing?.rollover||false);const [tag,setTag]=useState(existing?.tag||'');const [alerts,setAlerts]=useState(existing?.alerts!==false);const [warning,setWarning]=useState(String(existing?.warning??80));
 return <><Field label="Budget name" value={name} onChangeText={setName} maxLength={80}/><Field label="Period limit" value={amount} onChangeText={setAmount} placeholder="1800.00" keyboardType="decimal-pad"/><Section title="Period"/><View style={{flexDirection:'row',flexWrap:'wrap'}}>{(['monthly','weekly','custom'] as const).map(p=><Chip key={p} title={p} selected={period===p} onPress={()=>setPeriod(p)}/>)}</View><DateField label={period==='custom'?'Start date':'Rollover starts from'} value={start} onChangeText={setStart}/>{period==='custom'&&<DateField label="End date" value={end} onChangeText={setEnd}/>}<View style={[s.row,{marginBottom:16}]}><Text style={s.text}>Carry unused / overspent balance</Text><Switch value={rollover} disabled={period==='custom'} onValueChange={setRollover}/></View><Field label="Tag scope (optional)" value={tag} onChangeText={setTag} maxLength={60}/><View style={[s.row,{marginBottom:16}]}><Text style={s.text}>Budget alerts</Text><Switch value={alerts} onValueChange={setAlerts}/></View><Field label="Warning threshold (%)" value={warning} onChangeText={setWarning} keyboardType="number-pad" maxLength={2}/><Text style={s.label}>Budget scope</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}><Chip title="All expenses" selected={!category} onPress={()=>setCategory('')}/>{ledger.categories.filter(c=>c.type==='expense').map(c=><Chip key={c.id} title={c.name} selected={category===c.id} onPress={()=>setCategory(c.id)}/>)}</View><Text style={[s.muted,{marginVertical:14}]}>Refunds reduce spending. Overall and category limits are tracked independently. Enable notifications under Settings for threshold alerts.</Text><Btn title="Save budget" disabled={busy} onPress={async()=>{if(await act(()=>Store.saveBudget({id:existing?.id||Store.id(),name:name.trim(),amount:moneyToMinor(amount),categoryId:category})))onClose();}}/>{existing&&<Btn title="Delete budget" danger disabled={busy} onPress={()=>Alert.alert('Delete budget?','Your transactions will be kept.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{if(await act(()=>Store.removeItem('budgets',existing.id)))onClose();}}])}/>}</>;
}
export function GoalForm({existing,onClose}:{existing?:Goal;onClose:()=>void}){
 const {act,busy}=useApp();const [name,setName]=useState(existing?.name||'');const [target,setTarget]=useState(existing?minorToInput(existing.target):'');const [saved,setSaved]=useState(existing?minorToInput(existing.saved):'0');
 return <><Field label="Goal name" value={name} onChangeText={setName} placeholder="Emergency fund, holiday…" maxLength={80}/><Field label="Target amount" value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="1000.00"/><Field label="Amount already allocated" value={saved} onChangeText={setSaved} keyboardType="decimal-pad"/><Text style={[s.muted,{marginBottom:20}]}>A savings goal is an allocation tracker. It does not create an expense or change your account balances.</Text><Btn title="Save goal" disabled={busy} onPress={async()=>{if(await act(async()=>{const value=signedMoneyToMinor(saved);await Store.saveGoal({id:existing?.id||Store.id(),name:name.trim(),target:moneyToMinor(target),saved:value});}))onClose();}}/>{existing&&<Btn title="Delete goal" danger disabled={busy} onPress={()=>Alert.alert('Delete goal?','Your transactions and balances will be kept.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{if(await act(()=>Store.removeItem('goals',existing.id)))onClose();}}])}/>}</>;
}
