import React,{useState} from 'react';
import {View,Text} from 'react-native';
import {Page} from './screens';
import {Card,Chip,C,s} from './ui';
const lessons=[
 ['Start here','Choose your name, currency, first account and opening balance during setup. Opening balance is money you already have; it is not new income.\n\nUse Home for balances and recent activity. The bottom tabs open Transactions, Calendar, Statistics and More. Tap the + at the top to record a transaction.'],
 ['Add a transaction','Choose Expense for money spent, Income for money received, Transfer to move money between your accounts, or Refund to return spending. Enter the amount with the keypad, choose a category and payment type, then save.\n\nCash, Card and Account identify how you paid. Add or edit accounts under More → Accounts and select the correct account for each entry. Transfers do not count as income or expenses.\n\nTap Date & time to pick the day. Tap the time in the picker to use the round clock, choose hours and minutes, and select AM or PM. New entries start with the current time.\n\nExpand optional details for notes, tags and a receipt. Scroll to the Save button to finish.'],
 ['Edit and organize','Open Transactions to search notes or tags and filter by entry type or account. Tap an entry to edit it. Deleted entries can be restored using the temporary Undo button.\n\nIn the transaction category grid, hold a category and drag it to reorder. The final + tile adds a category. More → Categories lets you edit category names and icons; the three-dot icon option opens the larger icon picker.'],
 ['Calendar and reports','The calendar shows daily spending and income. Tap a day for its entries and net cash flow. Swipe horizontally or use the arrows to change month. Today returns to the current date; Agenda shows dates as a list. Scheduled items appear separately from recorded transactions.\n\nStatistics lets you select a period, compare it with the previous period and inspect charts and totals. Export CSV or PDF when needed. Exported reports contain readable financial information.'],
 ['Budgets and goals','More → Budgets sets spending limits for monthly, weekly or custom periods. Choose an overall budget or narrow it by category or tag. Rollover carries the previous period’s unused amount or overspending into the next period. Budget alerts need phone notification permission.\n\nMore → Savings goals records a target and contribution or withdrawal history. Goal tracking does not automatically move money between your accounts.'],
 ['Templates and recurring entries','More → Templates stores reusable transaction details for frequent entries. Open a template, review its amount and date, then save the transaction.\n\nMore → Recurring entries schedules daily, weekly, monthly or yearly items. Reminder mode asks you to record the transaction yourself. Automatic mode creates due entries when you open the app; it does not make payments. Large backlogs require review.'],
 ['Lending and borrowing','More → Debts tracks money lent or borrowed and repayments. Choose the account involved and record each repayment there. Walletway uses transfers so borrowed money and loan repayments do not inflate ordinary income or spending. Manage debt-linked records in Debts.'],
 ['Make it yours','More → Appearance selects Light, Dark or System theme and a primary color. Settings changes your name, number formatting, week start and Home card order. Tap the eye on Home to hide or show balances.\n\nSeparate currency ledgers keep records for each currency. Switching ledgers does not convert existing transactions. The rate calculator is an estimate using the rate you enter.'],
 ['Reminders and app lock','More → Settings enables the evening reminder and sets its time; the default is 8 PM. Allow notifications when asked. Notifications are handled on your phone. Delivery can be delayed by battery restrictions or force-stopping the app; reopen the app after a force-stop.\n\nEnable app lock to use the phone’s biometric or screen-lock authentication. This protects access to the app; the local database is not encrypted in this build.'],
 ['Back up and recover','More → Backup & restore exports an encrypted local backup. Save it somewhere safe and remember its passphrase: Walletway cannot recover it. Back up before uninstalling, changing phones or restoring another backup.\n\nRestoring replaces the current ledger after preview and confirmation. Recovery copies can help recover data from before a restore. Receipt attachments have backup size limits.\n\nGoogle backup is not configured in this build. Device sync is not available. Local backups are the supported way to move your records.'],
 ['Demo ads and troubleshooting','Home displays Google test banner ads when your connection and the privacy setup allow them. No paid ads are used. If an ad cannot load, the space stays hidden and the app retries automatically. No extra ad captions or show/hide controls appear.\n\nIf a form seems stuck, scroll inside the form; category reordering starts only after holding and dragging a tile. Check the selected ledger and filters if an entry seems missing. Never uninstall to troubleshoot before saving a backup.']
];
export function Guide(){const [selected,setSelected]=useState(0);return <Page><Card style={{backgroundColor:C.tealLight}}><Text style={s.heading}>Your Walletway guide</Text><Text style={[s.text,{marginTop:10,lineHeight:24}]}>Learn at your own pace. This guide works offline.</Text></Card><View style={{flexDirection:'row',flexWrap:'wrap'}}>{lessons.map(([title],i)=><Chip key={title} title={title} selected={i===selected} onPress={()=>setSelected(i)}/>)}</View><Card><Text accessibilityRole="header" style={s.section}>{lessons[selected][0]}</Text><Text selectable style={[s.text,{lineHeight:26,marginTop:14}]}>{lessons[selected][1]}</Text></Card><Text style={[s.muted,{marginTop:8}]}>Walletway 0.4.1 · Guide</Text></Page>;}
