import React,{useRef,useState} from 'react';
import {View,Text,Pressable,Animated,PanResponder,AccessibilityInfo} from 'react-native';
import {C,s,Icon} from './ui';
import {summary,filterTransactions,formatMoney,today} from './domain.cjs';
import type {Transaction} from './models';
type Props={month:Date;selected:string;transactions:Transaction[];currency:string;weekStart?:number;onNavigate:(step:number)=>void;onSelect:(date:string)=>void};
function compact(amount:number){const value=amount/100;const abs=Math.abs(value);return abs>=1000000?`${(value/1000000).toFixed(1)}M`:abs>=1000?`${(value/1000).toFixed(1)}K`:value.toFixed(2);}
export function MonthGrid(props:Props){
 const offset=useRef(new Animated.Value(0)).current;const [width,setWidth]=useState(300);const state=useRef({props,width});state.current={props,width};const animating=useRef(false);const reducedMotion=useRef(false);React.useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(value=>{reducedMotion.current=value;});const sub=AccessibilityInfo.addEventListener('reduceMotionChanged',value=>{reducedMotion.current=value;});return()=>sub.remove();},[]);
 function navigate(step:number){if(animating.current)return;if(reducedMotion.current){offset.setValue(0);state.current.props.onNavigate(step);return;}animating.current=true;const w=state.current.width;Animated.timing(offset,{toValue:-step*w,duration:150,useNativeDriver:true}).start(({finished})=>{if(!finished){offset.setValue(0);animating.current=false;return;}state.current.props.onNavigate(step);offset.setValue(step*w);Animated.timing(offset,{toValue:0,duration:180,useNativeDriver:true}).start(()=>{animating.current=false;});});}
 const responder=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>!animating.current&&Math.abs(g.dx)>14&&Math.abs(g.dx)>Math.abs(g.dy)*1.5,onPanResponderMove:(_,g)=>offset.setValue(Math.max(-state.current.width,Math.min(state.current.width,g.dx))),onPanResponderRelease:(_,g)=>{if(Math.abs(g.dx)>45||Math.abs(g.vx)>0.5)navigate(g.dx<0?1:-1);else Animated.spring(offset,{toValue:0,useNativeDriver:true}).start();},onPanResponderTerminate:()=>Animated.spring(offset,{toValue:0,useNativeDriver:true}).start()})).current;
 const y=props.month.getFullYear(),m=props.month.getMonth();const first=(new Date(y,m,1).getDay()-(props.weekStart??1)+7)%7;const count=new Date(y,m+1,0).getDate();
 return <><View style={[s.row,{marginBottom:14}]}><Pressable accessibilityRole="button" accessibilityLabel="Previous month" onPress={()=>navigate(-1)} style={{padding:12}}><Icon name="back"/></Pressable><Text style={s.section}>{props.month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Pressable accessibilityRole="button" accessibilityLabel="Next month" onPress={()=>navigate(1)} style={{padding:12}}><Icon name="next"/></Pressable></View><Text style={[s.muted,{marginBottom:12,fontSize:11}]}>Spent / Income · {props.currency} · K = thousand, M = million</Text><View style={{overflow:'hidden'}} onLayout={event=>setWidth(event.nativeEvent.layout.width)} {...responder.panHandlers}><Animated.View style={{transform:[{translateX:offset}]}}><View style={{flexDirection:'row'}}>{Array.from({length:7},(_,i)=>['S','M','T','W','T','F','S'][(i+(props.weekStart??1))%7]).map((day,i)=><Text key={i} style={[s.muted,{width:'14.2857%',textAlign:'center',marginBottom:8}]}>{day}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{Array.from({length:Math.ceil((first+count)/7)*7},(_,i)=>{const day=i-first+1;if(day<1||day>count)return <View key={i} style={{width:'14.2857%',height:84}}/>;const date=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const values=summary(filterTransactions(props.transactions,{from:date,to:date}));return <View key={date} style={{width:'14.2857%',padding:2}}><Pressable accessibilityRole="button" accessibilityLabel={`${date}. Spent ${formatMoney(values.spending,props.currency)}. Income ${formatMoney(values.income,props.currency)}.`} accessibilityState={{selected:props.selected===date}} onPress={()=>props.onSelect(date)} style={{height:80,alignItems:'center',justifyContent:'center',borderRadius:8,borderWidth:1,borderColor:props.selected===date?C.teal:C.line,backgroundColor:props.selected===date?C.tealLight:C.surface}}><View style={{width:24,height:24,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:props.selected===date?C.teal:date===today()?C.tealLight:'transparent'}}><Text style={{fontSize:12,color:props.selected===date?'white':C.ink,fontWeight:'700'}}>{day}</Text></View><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.7} style={{color:C.red,fontWeight:'700',fontSize:9,marginTop:7}}>{compact(values.spending)}</Text><Text numberOfLines={1} adjustsFontSizeToFit minimumFontScale={0.7} style={{color:C.green,fontWeight:'700',fontSize:9,marginTop:4}}>{compact(values.income)}</Text></Pressable></View>;})}</View></Animated.View></View><View style={[s.row,{marginTop:12}]}><Text style={{fontSize:11,color:C.red}}>Spent</Text><Text style={{fontSize:11,color:C.green}}>Income</Text><Text style={[s.muted,{fontSize:11}]}>Swipe ← next · previous →</Text></View></>;
}
