import React,{useState} from 'react';
import {View,Text,Alert,Switch,Pressable,Image} from 'react-native';
import {useApp} from './context';
import {Page} from './screens';
import {Card,Btn,Chip,Field,Section,Sheet,Empty,C,s} from './ui';
import {DateField} from './DateField';
import {ClockPicker} from './TimeField';
import {formatTime} from './time.cjs';
import {TransactionForm} from './forms';
import {today,moneyToMinor,signedMoneyToMinor,formatMoney,minorToInput,validDate} from './domain.cjs';
import {dueOccurrences,budgetUsage} from './planning.cjs';
import * as Store from './store';
import * as Local from './local';
import * as Backup from './backup';
import type {EntryTemplate,RecurringRule,Debt,Goal} from './models';
export function Templates(){const {ledger,act}=useApp();const [selected,setSelected]=useState<EntryTemplate>();return <Page><Text style={[s.muted,{marginBottom:16}]}>Save a reusable template from the Add Transaction form. Tap one to start a new transaction.</Text>{!(ledger.settings.templates||[]).length&&<Empty title="Your regular entries" body="Save a template for coffee, travel, salary or any entry you repeat."/>}{(ledger.settings.templates||[]).map(t=><Card key={t.id}><Text style={s.section}>{t.name}</Text><Text style={[s.muted,{marginVertical:12}]}>{t.type} · {formatMoney(t.amount,ledger.settings.currency)}</Text><Btn title="Use template" onPress={()=>setSelected(t)}/><Btn secondary title="Delete template" onPress={()=>Alert.alert('Delete template?','Saved transactions are kept.',[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>act(()=>Store.saveSettings({...ledger.settings,templates:(ledger.settings.templates||[]).filter(x=>x.id!==t.id)}))}])}/></Card>)}<Sheet visible={!!selected} title="New transaction from template" onClose={()=>setSelected(undefined)}>{selected&&<TransactionForm initialTemplate={selected} onDrag={()=>{}} onClose={()=>setSelected(undefined)}/>}</Sheet></Page>;}
export function Recurring(){const {ledger,act,busy}=useApp();const [open,setOpen]=useState(false);const [template,setTemplate]=useState('');const [date,setDate]=useState(today());const [interval,setInterval]=useState<RecurringRule['interval']>('monthly');const [mode,setMode]=useState<RecurringRule['mode']>('reminder');const [end,setEnd]=useState('');const [endEnabled,setEndEnabled]=useState(false);const rules=ledger.settings.recurring||[];
 async function save(){await act(async()=>{const t=ledger.settings.templates?.find(t=>t.id===template);if(!t)throw new Error('Save and choose an entry template first.');if(!validDate(date)||(endEnabled&&(!validDate(end)||end<date)))throw new Error('Choose valid schedule dates.');await Store.saveRule({...t,id:Store.id(),nextDate:date,interval,mode,enabled:true,anchorDay:Number(date.slice(8)),...(endEnabled?{endDate:end}:{})},ledger);setOpen(false);});}
 return <Page><Btn title="Add recurring entry" icon="plus" onPress={()=>setOpen(true)}/><Text style={[s.muted,{marginVertical:12}]}>Reminder-only is the default. Automatic entries are recorded when you open the app. Backlogs over 30 occurrences require review.</Text>{!rules.length&&<Empty title="Plan bills and income" body="Create a transaction template, then schedule it here."/>}{rules.map(r=>{const due=dueOccurrences(r);const ended=!!r.endDate&&r.nextDate>r.endDate;return <Card key={r.id}><View style={s.row}><Text style={[s.section,{flex:1}]}>{r.name}</Text><Switch value={r.enabled} onValueChange={enabled=>{act(()=>Store.saveRule({...r,enabled},ledger));}}/></View><Text style={[s.muted,{marginVertical:12}]}>{formatMoney(r.amount,ledger.settings.currency)} · {r.interval} · {r.mode}{ended?' · Finished':` · Next: ${r.nextDate}`}</Text>{due.dates.length>0&&<><Text style={[s.text,{marginBottom:10}]}>{due.needsReview?'Large backlog: review one occurrence at a time.':'Due for review: '+r.nextDate}</Text><Btn title={'Record '+r.nextDate} disabled={busy} onPress={()=>act(()=>Store.recordOccurrence(r,r.nextDate,ledger))}/><Btn secondary title="Skip this occurrence" disabled={busy} onPress={()=>act(()=>Store.recordOccurrence(r,r.nextDate,ledger,true))}/></>}<Btn secondary title="Remove schedule" onPress={()=>Alert.alert('Remove schedule?','Previously recorded entries stay in your ledger.',[{text:'Cancel'},{text:'Remove',style:'destructive',onPress:()=>act(()=>Store.saveSettings({...ledger.settings,recurring:rules.filter(x=>x.id!==r.id)}))}])}/></Card>;})}<Sheet visible={open} title="Recurring entry" onClose={()=>setOpen(false)}><Text style={s.label}>Entry template</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{(ledger.settings.templates||[]).map(t=><Chip key={t.id} title={t.name} selected={template===t.id} onPress={()=>setTemplate(t.id)}/>)}</View>{!ledger.settings.templates?.length&&<Text style={[s.muted,{marginVertical:12}]}>Open Add Transaction and save a template first.</Text>}<DateField label="First date" value={date} onChangeText={setDate}/><Section title="Repeat"/><View style={{flexDirection:'row',flexWrap:'wrap'}}>{(['daily','weekly','monthly','yearly'] as const).map(i=><Chip key={i} title={i} selected={interval===i} onPress={()=>setInterval(i)}/>)}</View><Section title="Entry mode"/><Chip title="Reminder only" selected={mode==='reminder'} onPress={()=>setMode('reminder')}/><Chip title="Automatic on app open" selected={mode==='automatic'} onPress={()=>setMode('automatic')}/><View style={[s.row,{marginVertical:16}]}><Text style={s.text}>End date</Text><Switch value={endEnabled} onValueChange={v=>{setEndEnabled(v);if(!end)setEnd(date);}}/></View>{endEnabled&&<DateField label="Last occurrence" value={end} onChangeText={setEnd}/>}<Btn title="Save schedule" disabled={busy} onPress={save}/></Sheet></Page>;
}
export function Debts(){const {ledger,act,busy}=useApp();const [open,setOpen]=useState(false);const [name,setName]=useState('');const [amount,setAmount]=useState('');const [direction,setDirection]=useState<Debt['direction']>('lent');const [account,setAccount]=useState(ledger.accounts.find(a=>!a.archived&&a.type!=='Debt')?.id||'');const [date,setDate]=useState(today());const [due,setDue]=useState(today());const [repaying,setRepaying]=useState<Debt>();const [payment,setPayment]=useState('');const [paymentDate,setPaymentDate]=useState(today());
 return <Page><Btn title="Record money lent or borrowed" icon="plus" onPress={()=>setOpen(true)}/><Text style={[s.muted,{marginVertical:12}]}>Principal and repayments move between your payment account and a receivable or liability account. They do not count as income or spending.</Text>{!(ledger.settings.debts||[]).length&&<Empty title="Keep track of repayments" body="Record who owes you, or whom you owe."/>}{(ledger.settings.debts||[]).map(d=>{const remaining=d.amount-d.payments.reduce((n,p)=>n+p.amount,0);return <Card key={d.id}><Text style={s.section}>{d.name}</Text><Text style={[s.muted,{marginVertical:10}]}>{d.direction==='lent'?'Owed to you':'You owe'} · Due {d.dueDate}</Text><Text style={[s.amount,{color:remaining&&d.dueDate<today()?C.red:C.ink}]}>{formatMoney(remaining,ledger.settings.currency)}</Text>{remaining>0&&<Btn title="Record repayment" onPress={()=>{setRepaying(d);setPayment('');setPaymentDate(today());}}/>}{d.payments.map(p=><Text key={p.id} style={[s.muted,{marginTop:6}]}>{p.date} · Repaid {formatMoney(p.amount,ledger.settings.currency)}</Text>)}</Card>;})}<Sheet visible={open} title="New debt" onClose={()=>setOpen(false)}><Field label="Person or description" value={name} onChangeText={setName} maxLength={80}/><Chip title="I lent money" selected={direction==='lent'} onPress={()=>setDirection('lent')}/><Chip title="I borrowed money" selected={direction==='borrowed'} onPress={()=>setDirection('borrowed')}/><Field label="Principal" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Section title="Payment account"/>{ledger.accounts.filter(a=>!a.archived&&a.type!=='Debt').map(a=><Chip key={a.id} title={a.name} selected={account===a.id} onPress={()=>setAccount(a.id)}/>)}<DateField label="Transaction date" value={date} onChangeText={setDate}/><DateField label="Repayment due" value={due} onChangeText={setDue}/><Btn title="Save debt" disabled={busy} onPress={()=>act(async()=>{const id=Store.id();await Store.saveDebt({id,name:name.trim(),direction,amount:moneyToMinor(amount),accountId:account,debtAccountId:'debt-account:'+id,date,dueDate:due,payments:[]},ledger);setOpen(false);setName('');setAmount('');})}/></Sheet><Sheet visible={!!repaying} title="Record repayment" onClose={()=>setRepaying(undefined)}><Field label="Amount repaid" value={payment} onChangeText={setPayment} keyboardType="decimal-pad"/><DateField label="Repayment date" value={paymentDate} onChangeText={setPaymentDate}/><Btn title="Save repayment" disabled={busy} onPress={()=>act(async()=>{if(repaying)await Store.repayDebt(repaying,moneyToMinor(payment),paymentDate,ledger);setRepaying(undefined);})}/></Sheet></Page>;
}
export function GoalAllocation({goal}:{goal:Goal}){const {ledger,act,busy}=useApp();const [open,setOpen]=useState(false);const [amount,setAmount]=useState('');return <><Btn secondary title="Add or withdraw allocation" onPress={()=>setOpen(true)}/>{(ledger.settings.goalContributions||[]).filter(c=>c.goalId===goal.id).slice(-5).reverse().map(c=><Text key={c.id} style={[s.muted,{marginTop:5}]}>{c.date} · {formatMoney(c.amount,ledger.settings.currency)}</Text>)}<Sheet visible={open} title={goal.name+' allocation'} onClose={()=>setOpen(false)}><Field label="Allocation (negative to withdraw)" value={amount} onChangeText={setAmount} keyboardType="numbers-and-punctuation"/><Text style={[s.muted,{marginBottom:16}]}>Allocations track your plan and do not change account balances.</Text><Btn title="Save allocation" disabled={busy} onPress={()=>act(async()=>{await Store.contributeGoal(goal,signedMoneyToMinor(amount),today(),ledger);setOpen(false);setAmount('');})}/></Sheet></>;}
export function Preferences(){const {ledger,act}=useApp();const settings=ledger.settings;const [clock,setClock]=useState(false);const [status,setStatus]=useState('');const save=(patch:Partial<typeof settings>)=>act(()=>Store.saveSettings({...settings,...patch}));
 async function notifications(key:'eveningReminder'|'budgetAlerts',enabled:boolean){if(enabled&&!await Local.requestNotifications()){setStatus('Notifications are disabled. Enable them in your phone’s app settings.');return;}await save({[key]:enabled});setStatus('');}
 return <><Section title="Reminders"/><Card><View style={s.row}><Text style={[s.text,{flex:1}]}>Evening expense reminder</Text><Switch value={!!settings.eveningReminder} onValueChange={v=>notifications('eveningReminder',v)}/></View><Pressable onPress={()=>setClock(true)} accessibilityRole="button" style={{paddingVertical:18}}><Text style={s.text}>Reminder time · {formatTime(settings.reminderTime||'20:00')}</Text></Pressable><Text style={[s.muted,{lineHeight:22}]}>Daily around this time, using your phone’s local notifications. Battery settings can delay delivery.</Text><View style={[s.row,{marginTop:16}]}><Text style={[s.text,{flex:1}]}>Budget threshold alerts</Text><Switch value={!!settings.budgetAlerts} onValueChange={v=>notifications('budgetAlerts',v)}/></View>{!!status&&<Text style={[s.muted,{marginTop:12}]}>{status}</Text>}<Btn secondary title="Test notification" onPress={async()=>{const granted=await Local.requestNotifications();if(granted)await (require('react-native').NativeModules.LocalFeatures.notifyOnce('test-'+Date.now(),'Walletway','Your local reminders are ready.'));else setStatus('Enable notifications in phone settings.');}}/></Card><ClockPicker visible={clock} value={settings.reminderTime||'20:00'} onClose={()=>setClock(false)} onChange={value=>{save({reminderTime:value});setClock(false);}}/>
 <Section title="Locale and calendar"/><Card><Text style={s.label}>Number formatting</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{[['en-IN','India'],['en-US','United States'],['en-GB','United Kingdom']].map(([locale,label])=><Chip key={locale} title={label} selected={(settings.locale||'en-IN')===locale} onPress={()=>save({locale})}/>)}</View><Text style={s.label}>First day of week</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{[[0,'Sunday'],[1,'Monday'],[6,'Saturday']].map(([day,label])=><Chip key={day} title={String(label)} selected={(settings.weekStart??1)===day} onPress={()=>save({weekStart:Number(day)})}/>)}</View></Card>
 <Section title="Privacy and data"/><Card><View style={s.row}><Text style={[s.text,{flex:1}]}>Lock app with biometrics or screen lock</Text><Switch value={!!settings.appLock} onValueChange={async enabled=>{await act(async()=>{if(await Local.authenticate())await Store.saveSettings({...settings,appLock:enabled});});}}/></View><Text style={[s.muted,{marginTop:10,lineHeight:22}]}>Uses supported biometrics or your phone’s PIN, pattern or password when opening the app. This does not encrypt the live database.</Text><Btn secondary title="Privacy policy" onPress={()=>Alert.alert('Walletway privacy','Financial records and receipts stay on your device. Local reminders use Android services. Exports contain your records and are shared only when you choose. Encrypted backups need your recovery passphrase. Google backup is not configured for UAT. Test advertising is optional and disabled by default. Uninstalling can delete local records. No analytics are added. Contact and store disclosures must be configured before public release.')}/><Btn danger title="Delete this ledger’s data" onPress={()=>Alert.alert('Delete this ledger’s local records?','This permanently clears the selected ledger, templates, debts, goals and attached receipts. Other currency ledgers are kept. Export an encrypted backup first.',[{text:'Cancel'},{text:'Delete everything',style:'destructive',onPress:()=>act(async()=>{await Local.clearReminders();await Store.deleteLocalData();})}])}/></Card></>;
}
export function RecoveryCopies(){const {act}=useApp();const [copies,setCopies]=useState<{path:string;date:string}[]>([]);const [preview,setPreview]=useState<any>();return <Page><Text style={[s.muted,{marginBottom:16}]}>Safety copies are stored privately before a restore. They can recover the previous ledger on this phone.</Text><Btn title="Find safety copies" onPress={()=>act(async()=>setCopies(await Backup.safetyCopies()))}/>{copies.map(c=><Card key={c.path}><Text style={s.text}>{c.date}</Text><Btn secondary title="Preview recovery" onPress={()=>act(async()=>setPreview(await Backup.readSafetyCopy(c.path)))}/></Card>)}{preview&&<Card><Text style={s.section}>Recovery preview</Text><Text style={[s.muted,{marginVertical:12}]}>{preview.data.transactions.length} transactions · {preview.createdAt}</Text><Btn title="Restore this copy" onPress={()=>Alert.alert('Replace current records?','A new safety copy will preserve the current ledger first.',[{text:'Cancel'},{text:'Restore',onPress:()=>act(async()=>{await Backup.safetySnapshot();await Store.restore(preview);setPreview(undefined);})}])}/></Card>}</Page>;}

export function CurrencyLedgers(){const {ledger,act}=useApp();const [rate,setRate]=useState('');const [amount,setAmount]=useState('');const [target,setTarget]=useState('USD');return <><Section title="Separate currency ledgers"/><Card><Text style={[s.muted,{marginBottom:14,lineHeight:22}]}>Each currency has its own records, balances and backups. Switching keeps the current ledger. Amounts in different currencies are never summed.</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['USD','INR','EUR','GBP','AUD','CAD'].map(currency=><Chip key={currency} title={currency} selected={currency===ledger.settings.currency} onPress={()=>Alert.alert('Open '+currency+' ledger?','This switches to a separate local ledger. Your current records are kept.',[{text:'Cancel'},{text:'Switch',onPress:()=>act(async()=>{await Local.clearReminders();await Store.switchLedger(currency);})}])}/>)}</View><Section title="Conversion estimate"/><Text style={[s.muted,{marginBottom:12}]}>Enter your own rate. This calculator does not move money or modify records.</Text><Field label={'Amount in '+ledger.settings.currency} value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Text style={s.label}>Target currency</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['USD','INR','EUR','GBP','AUD','CAD'].filter(c=>c!==ledger.settings.currency).map(c=><Chip key={c} title={c} selected={target===c} onPress={()=>setTarget(c)}/>)}</View><Field label={'1 '+ledger.settings.currency+' = target currency units'} value={rate} onChangeText={setRate} keyboardType="decimal-pad"/><Text style={s.amount}>{Number(amount)>=0&&Number(rate)>0&&Number.isFinite(Number(amount)*Number(rate))?formatMoney(Math.round(Number(amount)*Number(rate)*100),target):'Enter an amount and rate'}</Text></Card></>;}
