import {formatTime} from './time.cjs';
import {MonthGrid} from './MonthGrid';
import {DateField} from './DateField';
import {CategoryForm} from './CategoryForm';
import React,{useState,useEffect} from 'react';
import {View,Text,Pressable,ScrollView,FlatList,Alert,Switch} from 'react-native';
import {BannerAd,BannerAdSize,TestIds} from 'react-native-google-mobile-ads';
import {useApp} from './context';
import {Card,Btn,Chip,Field,Section,Icon,Empty,Sheet,Progress,C,s,PRIMARY_COLORS} from './ui';
import {TransactionForm,AccountForm,BudgetForm,GoalForm} from './forms';
import {Donut,Trend,Comparison} from './charts';
import {formatMoney,summary,filterTransactions,monthBounds,today,dayCount,accountBalance,validDate} from './domain.cjs';
import * as Store from './store';
import * as Backup from './backup';
import {GOOGLE_WEB_CLIENT_ID} from './config';
import type {Transaction,Account,Budget,Goal,Filter,Snapshot,Category} from './models';
export function Page({children}:{children:React.ReactNode}){return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingHorizontal:20,paddingBottom:32}}>{children}</ScrollView>;}
export function TransactionRow({item}:{item:Transaction}){
 const {ledger,edit}=useApp();const cat=ledger.categories.find(c=>c.id===item.categoryId);const account=ledger.accounts.find(a=>a.id===item.accountId);const dest=ledger.accounts.find(a=>a.id===item.destinationId);const positive=item.type==='income'||item.type==='refund';
 return <Pressable accessibilityRole="button" accessibilityLabel={`${cat?.name||'Transfer'}, ${formatMoney(item.amount,ledger.settings.currency)}, ${item.date}. Edit transaction.`} onPress={()=>edit(item)} style={[s.row,{paddingVertical:13,borderBottomWidth:1,borderBottomColor:C.line}]}><View style={[s.iconBox,{backgroundColor:positive?C.greenLight:'#FFF0EA'}]}><Icon name={cat?.icon||'transfer'} color={positive?C.green:C.red}/></View><View style={{flex:1}}><Text style={[s.text,{fontWeight:'700'}]} numberOfLines={1}>{cat?.name||`${account?.name} → ${dest?.name}`}</Text><Text style={[s.muted,{fontSize:11,marginTop:5}]} numberOfLines={1}>{item.date}{item.time?' · '+formatTime(item.time):''} · {item.note||account?.name}{item.type==='refund'?' · Refund':''}</Text></View><Text style={{fontSize:14,fontWeight:'700',color:item.type==='transfer'?C.muted:positive?C.green:C.red}}>{item.type==='transfer'?'':positive?'+':'−'}{formatMoney(item.amount,ledger.settings.currency)}</Text></Pressable>;
}
function TestAd(){const [failed,setFailed]=useState(false);if(failed)return null;return <View style={{alignItems:'center',marginTop:24,marginBottom:18}}><Text style={[s.muted,{fontSize:10,marginBottom:7}]}>Advertisement · test placement</Text><BannerAd unitId={TestIds.BANNER} size={BannerAdSize.ANCHORED_ADAPTIVE_BANNER} requestOptions={{requestNonPersonalizedAdsOnly:true}} onAdFailedToLoad={()=>setFailed(true)}/></View>;}
export function Home(){
 const {ledger,add,page}=useApp();const [hidden,setHidden]=useState(false);const currency=ledger.settings.currency;const bounds=monthBounds();const monthTx=filterTransactions(ledger.transactions,{from:bounds.from,to:today()});const totals=summary(monthTx);const balance=ledger.accounts.reduce((sum,a)=>sum+accountBalance(a,ledger.transactions),0);const day=summary(filterTransactions(ledger.transactions,{from:today(),to:today()}));const budget=ledger.budgets.find(b=>!b.categoryId);const money=(value:number)=>hidden?'••••':formatMoney(value,currency);const recent=filterTransactions(ledger.transactions,{}).slice(0,4);
 return <Page><View style={[s.row,{marginBottom:20,marginTop:6}]}><View><Text style={s.muted}>Your money, made simple.</Text><Text style={[s.heading,{marginTop:4}]}>Hi, {ledger.settings.name}</Text></View><View style={[s.row,{backgroundColor:C.tealLight,padding:9,borderRadius:12}]}><Icon name="shield" color={C.teal} size={16}/><Text style={{fontSize:11,color:C.teal,fontWeight:'700'}}>Saved locally</Text></View></View>
 <Card style={{backgroundColor:C.teal,borderColor:C.teal,padding:22}}><View style={s.row}><Text style={{color:'#D5EFEF',fontSize:14}}>Total balance</Text><Pressable accessibilityLabel={hidden?'Show balances':'Hide balances'} onPress={()=>setHidden(!hidden)} hitSlop={12}><Icon name="eye" color="white"/></Pressable></View><Text style={{fontSize:36,fontWeight:'800',color:'white',marginTop:15}}>{money(balance)}</Text><Text style={{color:'#D5EFEF',fontSize:12,marginTop:12}}>Across {ledger.accounts.length} account{ledger.accounts.length!==1?'s':''}</Text></Card>
 <View style={[s.row,{alignItems:'stretch'}]}>{[{title:'Income',value:totals.income,color:C.green,icon:'up'},{title:'Expenses',value:totals.spending,color:C.red,icon:'arrowDown'}].map(r=><Card key={r.title} style={{flex:1,padding:14}}><View style={[s.row,{justifyContent:'flex-start',gap:8}]}><Icon name={r.icon} color={r.color} size={18}/><Text style={s.muted}>{r.title}</Text></View><Text style={[s.amount,{fontSize:18,marginTop:10}]}>{money(r.value)}</Text><Text style={[s.muted,{fontSize:10,marginTop:5}]}>This month so far</Text></Card>)}</View>
 <Btn title="Add a transaction" icon="plus" onPress={add}/>
 <Card><View style={s.row}><Text style={s.section}>Today’s spending</Text><Text style={[s.amount,{color:C.red}]}>{money(day.spending)}</Text></View><View style={[s.row,{marginTop:16}]}><Text style={s.muted}>Daily average this month</Text><Text style={[s.text,{fontWeight:'700'}]}>{money(Math.round(totals.spending/dayCount(bounds.from,today())))}</Text></View></Card>
 {budget?<Pressable onPress={()=>page('Budgets')}><Card><View style={s.row}><Text style={s.section}>{budget.name}</Text><Icon name="next" size={18} color={C.muted}/></View><Text style={[s.muted,{marginTop:10}]}>{money(totals.spending)} of {money(budget.amount)}</Text><Progress value={totals.spending/budget.amount} color={totals.spending>budget.amount?C.red:C.teal}/><Text style={[s.muted,{marginTop:9,color:totals.spending>budget.amount?C.red:C.muted}]}>{totals.spending>budget.amount?'Over budget by ':'Remaining: '}{money(Math.abs(budget.amount-totals.spending))}</Text></Card></Pressable>:<Pressable onPress={()=>page('Budgets')}><Card style={{backgroundColor:C.tealLight}}><View style={s.row}><View style={{flex:1}}><Text style={s.section}>Give your money a plan</Text><Text style={[s.muted,{marginTop:6}]}>Set your first monthly budget.</Text></View><Icon name="target" color={C.teal}/></View></Card></Pressable>}
 <Section title="Recent transactions" action="See all" onPress={()=>page('Transactions')}/>{recent.length?<Card style={{paddingVertical:2}}>{recent.map(t=><TransactionRow key={t.id} item={t}/>)}</Card>:<Empty title="A fresh start" body="Add your first expense or income. Your charts and calendar will grow with you."/>}
 <TestAd/>
 </Page>;
}
export function Transactions(){
 const {ledger,add}=useApp();const [search,setSearch]=useState('');const [type,setType]=useState('');const [account,setAccount]=useState('');const [limit,setLimit]=useState(60);const list=filterTransactions(ledger.transactions,{search,type,accountId:account});const total=summary(list);
 return <FlatList data={list.slice(0,limit)} keyExtractor={t=>t.id} contentContainerStyle={{paddingHorizontal:20,paddingBottom:24}} keyboardShouldPersistTaps="handled" ListHeaderComponent={<><Field label="Search notes or tags" value={search} onChangeText={v=>{setSearch(v);setLimit(60);}} placeholder="Groceries, holiday, work…"/><ScrollView horizontal showsHorizontalScrollIndicator={false}>{['','expense','income','transfer','refund'].map(t=><Chip key={t} title={t?t[0].toUpperCase()+t.slice(1):'All'} selected={type===t} onPress={()=>{setType(t);setLimit(60);}}/>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false}><Chip title="All accounts" selected={!account} onPress={()=>setAccount('')}/>{ledger.accounts.map(a=><Chip key={a.id} title={a.name} selected={account===a.id} onPress={()=>setAccount(a.id)}/>)}</ScrollView><View style={[s.row,{marginVertical:16}]}><Text style={s.muted}>{list.length} transactions</Text><Text style={s.muted}>Net: {formatMoney(total.net,ledger.settings.currency)}</Text></View></>} renderItem={({item})=><TransactionRow item={item}/>} ListEmptyComponent={<Empty title={ledger.transactions.some(t=>!t.deletedAt)?'No matches':'No transactions yet'} body="Add a transaction or adjust your search and filters." action="Add transaction" onPress={add}/>} ListFooterComponent={list.length>limit?<View style={{marginTop:16}}><Btn secondary title="Load more" onPress={()=>setLimit(limit+60)}/></View>:null}/>;
}
export function Statistics(){
 const {ledger,act}=useApp();const [preset,setPreset]=useState('Month');const bounds=monthBounds();const [filter,setFilter]=useState<Filter>({from:bounds.from,to:today()});const [advanced,setAdvanced]=useState(false);const [min,setMin]=useState('');const [max,setMax]=useState('');
 const from=filter.from||bounds.from,to=filter.to||today();const valid=validDate(from)&&validDate(to)&&from<=to&&dayCount(from,to)<=3660;const minValue=min===''?undefined:Number(min)*100,maxValue=max===''?undefined:Number(max)*100;const amountsValid=(minValue===undefined||Number.isFinite(minValue)&&minValue>=0)&&(maxValue===undefined||Number.isFinite(maxValue)&&maxValue>=0)&&(minValue===undefined||maxValue===undefined||minValue<=maxValue);
 const list=valid&&amountsValid?filterTransactions(ledger.transactions,{...filter,min:minValue,max:maxValue}):[];const totals=summary(list);const currency=ledger.settings.currency;
 function choose(p:string){setPreset(p);let range={from:today(),to:today()};if(p==='Month')range={from:bounds.from,to:today()};if(p==='Last month'){const [y,m]=today().split('-').map(Number);range=monthBounds(today(new Date(y,m-2,1)));}if(p==='Year')range={from:today().slice(0,4)+'-01-01',to:today()};setFilter({...filter,...range});}
 return <Page><View style={s.row}><ScrollView horizontal showsHorizontalScrollIndicator={false}>{['Today','Month','Last month','Year'].map(p=><Chip key={p} title={p} selected={preset===p} onPress={()=>choose(p)}/>)}</ScrollView><Pressable accessibilityLabel="Show report filters" onPress={()=>setAdvanced(!advanced)} style={[s.iconBox,{backgroundColor:C.surface}]}><Icon name="filter" color={C.teal}/></Pressable></View>
 {advanced&&<Card><DateField label="From date" value={from} onChangeText={v=>{setPreset('Custom');setFilter({...filter,from:v});}}/><DateField label="To date" value={to} onChangeText={v=>{setPreset('Custom');setFilter({...filter,to:v});}}/><Text style={s.label}>Account</Text><ScrollView horizontal><Chip title="All" selected={!filter.accountId} onPress={()=>setFilter({...filter,accountId:''})}/>{ledger.accounts.map(a=><Chip key={a.id} title={a.name} selected={filter.accountId===a.id} onPress={()=>setFilter({...filter,accountId:a.id})}/>)}</ScrollView><Text style={s.label}>Type</Text><ScrollView horizontal>{['','expense','income','refund','transfer'].map(t=><Chip key={t} title={t||'All'} selected={(filter.type||'')===t} onPress={()=>setFilter({...filter,type:t})}/>)}</ScrollView><Text style={s.label}>Category</Text><ScrollView horizontal><Chip title="All" selected={!filter.categoryId} onPress={()=>setFilter({...filter,categoryId:''})}/>{ledger.categories.map(c=><Chip key={c.id} title={c.name} selected={filter.categoryId===c.id} onPress={()=>setFilter({...filter,categoryId:c.id})}/>)}</ScrollView><Field label="Note or tag search" value={filter.search||''} onChangeText={v=>setFilter({...filter,search:v})}/><View style={s.row}><View style={{flex:1}}><Field label="Minimum amount" value={min} onChangeText={setMin} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Maximum amount" value={max} onChangeText={setMax} keyboardType="decimal-pad"/></View></View><Btn title="Clear filters" secondary onPress={()=>{setFilter({from:bounds.from,to:today()});setPreset('Month');setMin('');setMax('');}}/></Card>}
 {!valid||!amountsValid?<Empty title="Check your filters" body="Use valid dates in order, a range of ten years or less, and valid minimum/maximum amounts."/>:<><Text style={[s.muted,{marginVertical:12}]}>{from} — {to} · {list.length} matching records</Text><Card><Text style={s.muted}>Net expenses</Text><Text style={[s.heading,{fontSize:32,marginTop:8}]}>{formatMoney(totals.spending,currency)}</Text><View style={[s.row,{marginTop:18}]}><View><Text style={s.muted}>Daily average</Text><Text style={[s.text,{fontWeight:'700',marginTop:5}]}>{formatMoney(Math.round(totals.spending/dayCount(from,to)),currency)}</Text></View><View><Text style={s.muted}>Savings rate</Text><Text style={[s.text,{fontWeight:'700',marginTop:5}]}>{totals.income>0?`${Math.round(totals.net/totals.income*100)}%`:'Not available'}</Text></View></View></Card><Donut transactions={list} categories={ledger.categories} currency={currency}/><Trend transactions={list} from={from} to={to} currency={currency}/><Comparison transactions={list} currency={currency}/><Btn title="Export filtered CSV" icon="export" secondary onPress={()=>Alert.alert('Export unencrypted CSV?','This report contains financial data. Save or share it only somewhere you trust.',[{text:'Cancel',style:'cancel'},{text:'Export',onPress:()=>act(()=>Backup.exportCSV({...ledger,transactions:list}))}])}/><Section title="Matching transactions"/>{list.slice(0,20).map(t=><TransactionRow key={t.id} item={t}/>)}{list.length>20&&<Text style={[s.muted,{marginTop:12}]}>Showing the first 20. Export the filtered report for the complete list.</Text>}</>}
 </Page>;
}
export function Calendar(){
 const {ledger,act,add}=useApp();const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const [selected,setSelected]=useState(today());const [note,setNote]=useState('');const journal=ledger.notes.find(n=>n.date===selected);
 useEffect(()=>{setNote(journal?.body||'');},[selected,journal?.body]);
 const y=month.getFullYear(),m=month.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,count=new Date(y,m+1,0).getDate();const cells=Array(Math.ceil((first+count)/7)*7).fill(0).map((_,i)=>i-first+1);const totals=summary(filterTransactions(ledger.transactions,{from:selected,to:selected}));const dayTx=filterTransactions(ledger.transactions,{from:selected,to:selected});const currency=ledger.settings.currency;
 function shift(n:number){const next=new Date(y,m+n,1);if(next.getFullYear()<1900||next.getFullYear()>2200)return;setMonth(next);setSelected(today(next));}
 return <Page><Card style={{padding:10}}><MonthGrid month={month} selected={selected} transactions={ledger.transactions} currency={currency} onNavigate={shift} onSelect={setSelected}/><Pressable accessibilityRole="button" onPress={()=>{setMonth(new Date(new Date().getFullYear(),new Date().getMonth(),1));setSelected(today());}} style={{alignSelf:'flex-end',padding:10}}><Text style={s.link}>Today</Text></Pressable></Card>
 <Section title={new Date(selected+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'})}/><View style={s.row}><Card style={{flex:1}}><Text style={s.muted}>Spent</Text><Text style={[s.amount,{color:C.red,marginTop:8}]}>{formatMoney(totals.spending,currency)}</Text></Card><Card style={{flex:1}}><Text style={s.muted}>Income</Text><Text style={[s.amount,{color:C.green,marginTop:8}]}>{formatMoney(totals.income,currency)}</Text></Card></View>
 {dayTx.length?<Card style={{paddingVertical:2}}>{dayTx.map(t=><TransactionRow key={t.id} item={t}/>)}</Card>:<Empty icon="calendar" title="No activity on this day" body="Your daily transactions will appear here." action="Add transaction" onPress={add}/>}
 <Section title="Daily money journal"/><Field label="Your note for this day" value={note} onChangeText={setNote} multiline placeholder="A small win, a spending reminder, a plan…"/><Btn title="Save daily note" secondary onPress={()=>act(()=>Store.saveNote({id:journal?.id||selected,date:selected,body:note.trim()}))}/>
 </Page>;
}
export function Accounts(){const {ledger}=useApp();const [editing,setEditing]=useState<Account|undefined>();const [open,setOpen]=useState(false);return <Page><Btn title="Add account" icon="plus" onPress={()=>{setEditing(undefined);setOpen(true);}}/>{ledger.accounts.map(a=><Pressable key={a.id} onPress={()=>{setEditing(a);setOpen(true);}}><Card><View style={s.row}><View style={[s.iconBox,{backgroundColor:C.tealLight}]}><Icon name="wallet" color={C.teal}/></View><View style={{flex:1}}><Text style={s.section}>{a.name}</Text><Text style={[s.muted,{marginTop:5}]}>{a.type}{a.archived?' · Archived':''}</Text></View><Text style={s.amount}>{formatMoney(accountBalance(a,ledger.transactions),ledger.settings.currency)}</Text></View></Card></Pressable>)}<Sheet visible={open} title={editing?'Edit account':'New account'} onClose={()=>setOpen(false)}><AccountForm key={editing?.id||'new'} existing={editing} onClose={()=>setOpen(false)}/></Sheet></Page>;}
export function Budgets(){
 const {ledger}=useApp();const [editing,setEditing]=useState<Budget|undefined>();const [open,setOpen]=useState(false);const list=filterTransactions(ledger.transactions,monthBounds());
 return <Page><Text style={[s.muted,{marginBottom:16}]}>Monthly limits · {new Date().toLocaleDateString('en-US',{month:'long',year:'numeric'})}</Text><Btn title="Create a budget" icon="plus" onPress={()=>{setEditing(undefined);setOpen(true);}}/>{!ledger.budgets.length&&<Empty icon="target" title="Make room for what matters" body="Set an overall monthly limit or plan a category like groceries."/>}{ledger.budgets.map(b=>{const amount=summary(b.categoryId?list.filter(t=>t.categoryId===b.categoryId):list).spending;return <Pressable key={b.id} onPress={()=>{setEditing(b);setOpen(true);}}><Card><View style={s.row}><Text style={s.section}>{b.name}</Text><Text style={{color:amount>b.amount?C.red:C.teal,fontWeight:'700'}}>{Math.round(amount/b.amount*100)}%</Text></View><Text style={[s.muted,{marginTop:10}]}>{formatMoney(amount,ledger.settings.currency)} of {formatMoney(b.amount,ledger.settings.currency)}</Text><Progress value={amount/b.amount} color={amount>b.amount?C.red:C.teal}/><Text style={[s.muted,{marginTop:12,color:amount>b.amount?C.red:C.muted}]}>{amount>b.amount?'Over budget: ':'Remaining: '}{formatMoney(Math.abs(b.amount-amount),ledger.settings.currency)}</Text></Card></Pressable>;})}<Sheet visible={open} title={editing?'Edit budget':'New budget'} onClose={()=>setOpen(false)}><BudgetForm key={editing?.id||'new'} existing={editing} onClose={()=>setOpen(false)}/></Sheet></Page>;
}
export function Goals(){const {ledger}=useApp();const [editing,setEditing]=useState<Goal|undefined>();const [open,setOpen]=useState(false);return <Page><Btn title="Add a savings goal" icon="plus" onPress={()=>{setEditing(undefined);setOpen(true);}}/>{!ledger.goals.length&&<Empty icon="target" title="Dream it. Plan it." body="Track what you’ve allocated for an emergency fund, a trip, or something you love."/>}{ledger.goals.map(g=><Pressable key={g.id} onPress={()=>{setEditing(g);setOpen(true);}}><Card><View style={s.row}><Text style={s.section}>{g.name}</Text>{g.saved>=g.target&&<Icon name="check" color={C.green}/>}</View><Text style={[s.muted,{marginTop:12}]}>{formatMoney(g.saved,ledger.settings.currency)} of {formatMoney(g.target,ledger.settings.currency)}</Text><Progress value={g.saved/g.target}/><Text style={[s.link,{marginTop:12}]}>{g.saved>=g.target?'Goal reached!':`${Math.round(g.saved/g.target*100)}% saved`}</Text></Card></Pressable>)}<Sheet visible={open} title={editing?'Edit goal':'New savings goal'} onClose={()=>setOpen(false)}><GoalForm key={editing?.id||'new'} existing={editing} onClose={()=>setOpen(false)}/></Sheet></Page>;}
export function BackupScreen(){
 const {ledger,act,busy}=useApp();const [pass,setPass]=useState('');const [confirm,setConfirm]=useState('');const [email,setEmail]=useState('');const [files,setFiles]=useState<{id:string;createdTime:string;name:string;size?:string}[]>([]);const [preview,setPreview]=useState<Snapshot|null>(null);
 function checkPass(){if(pass.length<12)throw new Error('Use a recovery passphrase with at least 12 characters.');if(pass!==confirm)throw new Error('Recovery passphrases do not match.');}
 async function exportLocal(){await act(async()=>{checkPass();await Backup.exportBackup(pass);});}
 async function importLocal(){await act(async()=>{if(pass.length<12)throw new Error('Enter your original recovery passphrase.');const result=await Backup.importBackup(pass);if(result)setPreview(result);});}
 function restore(){if(!preview)return;const selected=preview;Alert.alert('Replace current data?','This replaces transactions, accounts, budgets, notes, and goals. A private safety copy will be made first.',[{text:'Cancel',style:'cancel'},{text:'Replace data',style:'destructive',onPress:async()=>{if(await act(async()=>{await Backup.safetySnapshot();await Store.restore(selected);})){setPreview(null);setPass('');setConfirm('');Alert.alert('Restored','Your financial data has been restored.');}}}]);}
 return <Page><Card style={{alignItems:'center',backgroundColor:C.tealLight,paddingVertical:26}}><Icon name="shield" size={52} color={C.teal}/><Text style={[s.section,{textAlign:'center',marginTop:16}]}>Keep your money history safe</Text><Text style={[s.muted,{textAlign:'center',lineHeight:21,marginTop:9}]}>Encrypted backups. Your choice of local files or your private Google Drive app data.</Text></Card>
 <Card><Text style={s.section}>Recovery passphrase</Text><Text style={[s.muted,{lineHeight:21,marginVertical:12}]}>Use at least 12 characters. Keep this secret somewhere safe: you need it on a new device, and Google cannot recover it.</Text><Field label="Recovery passphrase" value={pass} onChangeText={setPass} secureTextEntry maxLength={200}/><Field label="Confirm for a new backup" value={confirm} onChangeText={setConfirm} secureTextEntry maxLength={200}/><Text style={s.muted}>For restore, enter the original passphrase above. It is not stored by this app.</Text></Card>
 <Section title="Local backup"/><Btn title={busy?'Working…':'Export encrypted backup'} icon="export" disabled={busy} onPress={exportLocal}/><Btn title="Restore a local backup" secondary disabled={busy} onPress={importLocal}/>
 <Section title="Google Drive backup"/>{!GOOGLE_WEB_CLIENT_ID&&<Card><Text style={s.section}>Google setup required</Text><Text style={[s.muted,{lineHeight:21,marginTop:8}]}>This build needs the developer’s Google OAuth configuration to enable sign-in. Local encrypted backups work independently.</Text></Card>}
 {email?<Card><Text style={s.section}>Connected to Google</Text><Text style={[s.muted,{marginTop:6}]}>{email}</Text><Text style={[s.muted,{marginTop:10}]}>Last verified upload: {ledger.settings.lastBackup?new Date(ledger.settings.lastBackup).toLocaleString():'No backup yet'}</Text></Card>:<Btn title="Connect Google" secondary disabled={busy||!GOOGLE_WEB_CLIENT_ID} onPress={()=>act(async()=>{setEmail(await Backup.connectGoogle());})}/>}
 {email&&<><Btn title="Back up to Google now" icon="cloud" disabled={busy} onPress={()=>act(async()=>{checkPass();const timestamp=await Backup.googleBackup(pass);await Store.saveSettings({...ledger.settings,lastBackup:timestamp});Alert.alert('Backup verified','Your encrypted snapshot was uploaded and verified.');})}/><Btn title="Find Google backups" secondary disabled={busy} onPress={()=>act(async()=>{setFiles(await Backup.googleSnapshots());})}/><Btn title="Disconnect Google" secondary disabled={busy} onPress={()=>act(async()=>{await Backup.disconnectGoogle();setEmail('');setFiles([]);})}/></>}
 {files.map(f=><Pressable key={f.id} disabled={busy} onPress={()=>act(async()=>{if(Number(f.size||0)>25*1024*1024)throw new Error('Backup exceeds the 25 MB safety limit.');setPreview(await Backup.readGoogleSnapshot(f.id,pass));})}><Card><Text style={s.text}>{new Date(f.createdTime).toLocaleString()}</Text><Text style={[s.muted,{marginTop:6}]} numberOfLines={1}>{f.name}</Text><Text style={[s.link,{marginTop:8}]}>Preview restore</Text></Card></Pressable>)}
 <Card style={{marginTop:18}}><Text style={s.section}>Backup, not device sync</Text><Text style={[s.muted,{lineHeight:21,marginTop:8}]}>This version uploads a snapshot when you request it. Restore replaces your ledger; it does not merge edits from multiple devices. Changes after the last backup are only on this device.</Text></Card>
 <Sheet visible={!!preview} title="Restore preview" onClose={()=>setPreview(null)}>{preview&&<><Card><Text style={s.section}>Backup from {new Date(preview.createdAt).toLocaleString()}</Text><Text style={[s.text,{lineHeight:26,marginTop:14}]}>{preview.data.transactions.filter(t=>!t.deletedAt).length} transactions{'\n'}{preview.data.accounts.length} accounts{'\n'}{preview.data.budgets.length} budgets{'\n'}{preview.data.goals.length} savings goals{'\n'}Currency: {preview.data.settings.currency}</Text></Card><Text style={[s.muted,{lineHeight:22,marginBottom:20}]}>Restore replaces current data. A private local safety copy is created first.</Text><Btn title="Replace data with this backup" danger disabled={busy} onPress={restore}/></>}</Sheet>
 </Page>;
}
export function More(){const {ledger,page}=useApp();const rows=[['Appearance','filter','Theme and primary color'],['Categories','basket','Add and edit expense and income categories'],['Accounts','wallet','Cash, bank, cards and transfers'],['Budgets','target','Plan your monthly spending'],['Savings goals','star','Make progress toward your goals'],['Backup & restore','cloud','Encrypted local and Google backups'],['Settings','filter','Profile, currency and privacy']];return <Page><Card style={{backgroundColor:C.tealLight}}><View style={s.row}><View style={[s.iconBox,{backgroundColor:C.teal}]}><Text style={{color:'white',fontWeight:'800',fontSize:18}}>{ledger.settings.name.slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.section}>{ledger.settings.name}</Text><Text style={[s.muted,{marginTop:5}]}>Your personal money space</Text></View></View></Card>{rows.map(([title,icon,desc])=><Pressable key={title} onPress={()=>page(title)}><Card><View style={s.row}><Icon name={icon} color={C.teal}/><View style={{flex:1,marginLeft:8}}><Text style={[s.text,{fontWeight:'700'}]}>{title}</Text><Text style={[s.muted,{marginTop:6}]}>{desc}</Text></View><Icon name="next" size={18} color={C.muted}/></View></Card></Pressable>)}<Text style={[s.muted,{textAlign:'center',marginTop:16}]}>Moneywise 0.3.1 · Offline first</Text></Page>;}
export function Settings(){const {ledger,act,busy}=useApp();const [name,setName]=useState(ledger.settings.name);const [currency,setCurrency]=useState(ledger.settings.currency);const locked=ledger.transactions.some(t=>!t.deletedAt)||ledger.budgets.length>0||ledger.goals.length>0||ledger.accounts.some(a=>a.opening!==0);return <Page><Card><Field label="Your name" value={name} onChangeText={setName} maxLength={60}/><Text style={s.label}>Ledger currency</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['USD','INR','EUR','GBP','AUD','CAD'].map(c=><Chip key={c} title={c} selected={currency===c} onPress={()=>{if(locked&&c!==currency)Alert.alert('Currency is locked','Changing currency would relabel existing amounts. Use a separate ledger or restore a backup in the intended currency.');else setCurrency(c);}}/>)}</View><Text style={[s.muted,{marginVertical:12}]}>One currency per ledger. Existing amounts are never silently converted.</Text><Btn title="Save settings" disabled={busy} onPress={()=>act(async()=>{if(!name.trim())throw new Error('Enter your name.');await Store.saveSettings({...ledger.settings,name:name.trim(),currency});})}/></Card><Section title="Your privacy"/><Card><Text style={[s.text,{lineHeight:25}]}>Financial records stay in the local SQLite database. Google receives an encrypted backup only when you connect and upload. Ads in this build are test ads and receive no financial records.</Text><View style={s.divider}/><Text style={[s.muted,{lineHeight:22}]}>Uninstalling or losing your phone can remove local data. Export a backup regularly. The recovery passphrase cannot be recovered by the app. The local database itself is not encrypted in this build.</Text></Card><Btn title="Export all transactions as CSV" secondary icon="export" onPress={()=>Alert.alert('Export unencrypted CSV?','The exported file contains your financial data.',[{text:'Cancel',style:'cancel'},{text:'Export',onPress:()=>act(()=>Backup.exportCSV(ledger))}])}/></Page>;}
export function Onboarding(){const {ledger,act,busy}=useApp();const [name,setName]=useState('');const [currency,setCurrency]=useState('USD');return <Page><View style={{alignItems:'center',paddingTop:38,paddingBottom:28}}><View style={[s.iconBox,{width:86,height:86,borderRadius:28,backgroundColor:C.teal}]}><Icon name="wallet" size={44} color="white"/></View><Text style={[s.heading,{fontSize:34,marginTop:24}]}>Meet Moneywise</Text><Text style={[s.muted,{fontSize:16,textAlign:'center',lineHeight:24,marginTop:12}]}>A little clarity for your everyday money.</Text></View><Card><Field label="What should we call you?" value={name} onChangeText={setName} placeholder="Your name (optional)" maxLength={60}/><Text style={s.label}>Choose your currency</Text><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['USD','INR','EUR','GBP','AUD','CAD'].map(c=><Chip key={c} title={c} selected={c===currency} onPress={()=>setCurrency(c)}/>)}</View></Card><View style={{marginVertical:14,gap:14}}>{[['shield','Works offline. No account required.'],['chart','See your spending in charts and calendars.'],['cloud','Export encrypted backups when you’re ready.']].map(([icon,text])=><View key={icon} style={[s.row,{justifyContent:'flex-start'}]}><Icon name={icon} color={C.teal}/><Text style={[s.text,{flex:1,fontSize:14}]}>{text}</Text></View>)}</View><Btn title="Let’s get started" disabled={busy} onPress={()=>act(()=>Store.saveSettings({...ledger.settings,name:name.trim()||'Friend',currency,onboarding:true}))}/><Text style={[s.muted,{textAlign:'center',lineHeight:20}]}>A Cash account is ready for you. Add more accounts anytime.</Text></Page>;}

export function Categories(){
 const {ledger}=useApp();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Category|undefined>();const [type,setType]=useState<'expense'|'income'>('expense');
 return <Page><View style={{flexDirection:'row'}}>{(['expense','income'] as const).map(t=><Chip key={t} title={t==='expense'?'Expenses':'Income'} selected={type===t} onPress={()=>setType(t)}/>)}</View><Btn title="Add category" icon="plus" onPress={()=>{setEditing(undefined);setOpen(true);}}/>{ledger.categories.filter(c=>c.type===type).map(c=><Pressable key={c.id} accessibilityRole="button" accessibilityLabel={`Edit ${c.name}`} onPress={()=>{setEditing(c);setOpen(true);}}><Card><View style={s.row}><Icon name={c.icon} color={c.color}/><Text style={[s.text,{flex:1}]}>{c.name}</Text><Text style={s.link}>Edit</Text></View></Card></Pressable>)}<Sheet visible={open} title={editing?'Edit category':'Add category'} onClose={()=>setOpen(false)}>{open&&<CategoryForm key={editing?.id||type+'new'} existing={editing} type={type} onClose={()=>setOpen(false)}/>}</Sheet></Page>;
}

export function Appearance(){const {ledger,act,busy}=useApp();return <Page><Section title="Appearance"/><Card><Text style={s.label}>Theme</Text><View style={{flexDirection:'row'}}>{(['light','dark'] as const).map(theme=><Chip key={theme} title={theme==='light'?'Light':'Dark'} selected={(ledger.settings.theme||'light')===theme} onPress={()=>act(()=>Store.saveSettings({...ledger.settings,theme}))}/>)}</View><Text style={[s.label,{marginTop:16}]}>Primary color</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{PRIMARY_COLORS.map(color=><Pressable key={color} accessibilityRole="button" accessibilityLabel={`Primary color ${color}`} accessibilityState={{selected:(ledger.settings.primaryColor||PRIMARY_COLORS[0])===color}} disabled={busy} onPress={()=>act(()=>Store.saveSettings({...ledger.settings,primaryColor:color}))} style={{width:48,height:48,borderRadius:24,backgroundColor:color,alignItems:'center',justifyContent:'center'}}>{(ledger.settings.primaryColor||PRIMARY_COLORS[0])===color&&<Icon name="check" color="white"/>}</Pressable>)}</View></Card></Page>;}
