import React,{useState,useEffect,useRef} from 'react';
import {View,Text,Pressable,useWindowDimensions,GestureResponderEvent} from 'react-native';
import Svg,{Circle,Line} from 'react-native-svg';
import {Sheet,Btn,Chip,C,s} from './ui';
import {currentTime,parseTime,to24Hour,clockValue} from './time.cjs';
export {currentTime} from './time.cjs';
export function ClockPicker({visible,value,onChange,onClose}:{visible:boolean;value:string;onChange:(value:string)=>void;onClose:()=>void}){
 const [hour,setHour]=useState(12);const [minute,setMinute]=useState(0);const [period,setPeriod]=useState<'AM'|'PM'>('AM');const [mode,setMode]=useState<'hour'|'minute'>('hour');const [dragging,setDragging]=useState(false);
 const {width}=useWindowDimensions();const size=Math.min(280,width-64);const center=size/2;const radius=center-28;const dial=useRef<View>(null);const origin=useRef({x:0,y:0});
 useEffect(()=>{if(visible){const t=parseTime(value||currentTime());setHour(t.hour);setMinute(t.minute);setPeriod(t.period);setMode('hour');setDragging(false);}},[visible]);
 function choose(e:GestureResponderEvent){const x=e.nativeEvent.pageX-origin.current.x-center;const y=e.nativeEvent.pageY-origin.current.y-center;if(Math.hypot(x,y)<20)return;const v=clockValue(x,y,mode);if(mode==='hour')setHour(v);else setMinute(v);}
 function finish(){setDragging(false);if(mode==='hour')setMode('minute');}
 const selection=mode==='hour'?hour%12:minute;const angle=selection/(mode==='hour'?12:60)*Math.PI*2;const handX=center+Math.sin(angle)*radius;const handY=center-Math.cos(angle)*radius;
 return <Sheet visible={visible} title="Choose time" onClose={onClose} scrollEnabled={!dragging}><View style={{alignItems:'center'}}><View style={[s.row,{justifyContent:'center',marginBottom:14}]}><Pressable accessibilityRole="button" accessibilityLabel="Select hours" onPress={()=>setMode('hour')} style={{padding:10,borderRadius:12,backgroundColor:mode==='hour'?C.tealLight:C.surface}}><Text style={[s.heading,{fontSize:36,color:mode==='hour'?C.teal:C.ink}]}>{hour}</Text></Pressable><Text style={[s.heading,{fontSize:32}]}>:</Text><Pressable accessibilityRole="button" accessibilityLabel="Select minutes" onPress={()=>setMode('minute')} style={{padding:10,borderRadius:12,backgroundColor:mode==='minute'?C.tealLight:C.surface}}><Text style={[s.heading,{fontSize:36,color:mode==='minute'?C.teal:C.ink}]}>{String(minute).padStart(2,'0')}</Text></Pressable></View><View style={{flexDirection:'row'}}>{(['AM','PM'] as const).map(p=><Chip key={p} title={p} selected={period===p} onPress={()=>setPeriod(p)}/>)}</View><Text style={[s.muted,{marginBottom:14}]}>Tap or drag the clock hand to choose {mode==='hour'?'an hour':'minutes'}.</Text>
 <View ref={dial} onLayout={()=>dial.current?.measureInWindow((x,y)=>{origin.current={x,y};})} onStartShouldSetResponder={()=>true} onMoveShouldSetResponderCapture={()=>true} onResponderGrant={e=>{e.persist();setDragging(true);dial.current?.measureInWindow((x,y)=>{origin.current={x,y};choose(e);});}} onResponderMove={choose} onResponderRelease={finish} onResponderTerminate={()=>setDragging(false)} onResponderTerminationRequest={()=>false} style={{width:size,height:size,borderRadius:center,backgroundColor:C.bg,marginBottom:20}}>
 <Svg pointerEvents="none" width={size} height={size} style={{position:'absolute'}}><Circle cx={center} cy={center} r={center-1} stroke={C.line} fill="none"/>{Array.from({length:60},(_,i)=>{const a=i/60*Math.PI*2;return <Line key={i} x1={center+Math.sin(a)*(center-8)} y1={center-Math.cos(a)*(center-8)} x2={center+Math.sin(a)*(center-(i%5===0?16:12))} y2={center-Math.cos(a)*(center-(i%5===0?16:12))} stroke={C.muted} strokeWidth={i%5===0?1.5:0.6}/>;})}<Line x1={center} y1={center} x2={handX} y2={handY} stroke={C.teal} strokeWidth={3}/><Circle cx={center} cy={center} r={5} fill={C.teal}/><Circle cx={handX} cy={handY} r={20} fill={C.teal}/></Svg>
 {Array.from({length:12},(_,i)=>{const n=mode==='hour'?(i||12):i*5;const a=i/12*Math.PI*2;const selected=mode==='hour'?hour===n:minute===n;return <Pressable key={i} accessibilityRole="button" accessibilityLabel={`${n} ${mode==='hour'?'hours':'minutes'}`} accessibilityState={{selected}} onPress={()=>{if(mode==='hour'){setHour(n);setMode('minute');}else setMinute(n);}} style={{position:'absolute',left:center+Math.sin(a)*radius-20,top:center-Math.cos(a)*radius-20,width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'}}><Text style={{color:selected?'white':C.ink,fontSize:16,fontWeight:'600'}}>{mode==='hour'?n:String(n).padStart(2,'0')}</Text></Pressable>;})}
 </View><Text accessibilityLiveRegion="polite" style={[s.text,{marginBottom:12}]}>Selected: {hour}:{String(minute).padStart(2,'0')} {period}</Text><View style={s.row}><Btn title="−1 minute" secondary onPress={()=>{setMode('minute');setMinute(v=>(v+59)%60);}}/><Btn title="+1 minute" secondary onPress={()=>{setMode('minute');setMinute(v=>(v+1)%60);}}/></View></View><Btn title="Use selected time" onPress={()=>{onChange(to24Hour(hour,minute,period));onClose();}}/><Btn title="Cancel" secondary onPress={onClose}/></Sheet>;
}
